/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FolderExplorer: typeof import('./components/FolderExplorer.vue')['default']
    OCRResultView: typeof import('./components/OCRResultView.vue')['default']
    OCRViewer: typeof import('./components/OCRViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
